x-common:
  database: &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password 'Hieu2004'
    MYSQL_ROOT_PASSWORD: 'Hieu2004'
  panel: &panel-environment
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: 'UTC'
    APP_SERVICE_AUTHOR: 'noreply@example.com'
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail: &mail-environment
    MAIL_FROM: 'noreply@example.com'
    MAIL_DRIVER: 'smtp'
    MAIL_HOST: 'mail'
    MAIL_PORT: '1025'
    MAIL_USERNAME: ''
    MAIL_PASSWORD: ''
    MAIL_ENCRYPTION: 'true'

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      <<: *db-environment
      MYSQL_DATABASE: 'panel'
      MYSQL_USER: 'pterodactyl'
  cache:
    image: redis:alpine
    ports:
      - '6379:6379'

  panel:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database
      - cache
    ports:
      - '5173:5173'
      - '80:80'
    volumes:
      - './srv/pterodactyl/var/:/app/var/'
      - './srv/pterodactyl/nginx/:/etc/nginx/http.d/'
      - './srv/pterodactyl/certs/:/etc/letsencrypt/'
      - './srv/pterodactyl/logs/:/app/storage/logs'
      - './resources:/app/resources'
      - './app/:/app/app'
    environment:
      <<: [ *panel-environment, *mail-environment ]
      APP_ENV: 'development'
      APP_ENVIRONMENT_ONLY: 'false'
      CACHE_DRIVER: 'redis'
      DB_DATABASE: 'panel'
      SESSION_DRIVER: 'redis'
      QUEUE_DRIVER: 'redis'
      REDIS_HOST: 'cache'
      DB_CONNECTION: 'mariadb'
      DB_USERNAME: 'pterodactyl'
      DB_PASSWORD: *db-password
      DB_HOST: 'database'
      DB_PORT: '3306'
      HASHIDS_LENGTH: 8
networks:
  default:
volumes:
  db:
